/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as DiscoverSlugRouteImport } from './routes/discover.$slug'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSlugRoute = DiscoverSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiscoverRoute,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TripsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/explore': typeof ExploreRoute
  '/packages': typeof PackagesRoute
  '/trips': typeof TripsRouteWithChildren
  '/discover/$slug': typeof DiscoverSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/explore': typeof ExploreRoute
  '/packages': typeof PackagesRoute
  '/trips': typeof TripsRouteWithChildren
  '/discover/$slug': typeof DiscoverSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/explore': typeof ExploreRoute
  '/packages': typeof PackagesRoute
  '/trips': typeof TripsRouteWithChildren
  '/discover/$slug': typeof DiscoverSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/explore'
    | '/packages'
    | '/trips'
    | '/discover/$slug'
    | '/trips/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/explore'
    | '/packages'
    | '/trips'
    | '/discover/$slug'
    | '/trips/$slug'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/explore'
    | '/packages'
    | '/trips'
    | '/discover/$slug'
    | '/trips/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  PackagesRoute: typeof PackagesRoute
  TripsRoute: typeof TripsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$slug': {
      id: '/discover/$slug'
      path: '/$slug'
      fullPath: '/discover/$slug'
      preLoaderRoute: typeof DiscoverSlugRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof TripsRoute
    }
  }
}

interface DiscoverRouteChildren {
  DiscoverSlugRoute: typeof DiscoverSlugRoute
}

const DiscoverRouteChildren: DiscoverRouteChildren = {
  DiscoverSlugRoute: DiscoverSlugRoute,
}

const DiscoverRouteWithChildren = DiscoverRoute._addFileChildren(
  DiscoverRouteChildren,
)

interface TripsRouteChildren {
  TripsSlugRoute: typeof TripsSlugRoute
}

const TripsRouteChildren: TripsRouteChildren = {
  TripsSlugRoute: TripsSlugRoute,
}

const TripsRouteWithChildren = TripsRoute._addFileChildren(TripsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRouteWithChildren,
  ExploreRoute: ExploreRoute,
  PackagesRoute: PackagesRoute,
  TripsRoute: TripsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
