/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForAgentsRouteImport } from './routes/for-agents'
import { Route as ForPartnersRouteImport } from './routes/for-partners'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as ConceptsIndexRouteImport } from './routes/concepts.index'
import { Route as ConceptsSlugRouteImport } from './routes/concepts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsRoute = ForAgentsRouteImport.update({
  id: '/for-agents',
  path: '/for-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPartnersRoute = ForPartnersRouteImport.update({
  id: '/for-partners',
  path: '/for-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsIndexRoute = ConceptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConceptsRoute,
} as any)
const ConceptsSlugRoute = ConceptsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConceptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concepts': typeof ConceptsRouteWithChildren
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-partners': typeof ForPartnersRoute
  '/journey': typeof JourneyRoute
  '/packages': typeof PackagesRoute
  '/style-guide': typeof StyleGuideRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/concepts/': typeof ConceptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-partners': typeof ForPartnersRoute
  '/journey': typeof JourneyRoute
  '/packages': typeof PackagesRoute
  '/style-guide': typeof StyleGuideRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/concepts': typeof ConceptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concepts': typeof ConceptsRouteWithChildren
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/for-agents': typeof ForAgentsRoute
  '/for-partners': typeof ForPartnersRoute
  '/journey': typeof JourneyRoute
  '/packages': typeof PackagesRoute
  '/style-guide': typeof StyleGuideRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/concepts/': typeof ConceptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/concepts'
    | '/contact'
    | '/explore'
    | '/for-agents'
    | '/for-partners'
    | '/journey'
    | '/packages'
    | '/style-guide'
    | '/concepts/$slug'
    | '/concepts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/for-agents'
    | '/for-partners'
    | '/journey'
    | '/packages'
    | '/style-guide'
    | '/concepts/$slug'
    | '/concepts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/concepts'
    | '/contact'
    | '/explore'
    | '/for-agents'
    | '/for-partners'
    | '/journey'
    | '/packages'
    | '/style-guide'
    | '/concepts/$slug'
    | '/concepts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConceptsRoute: typeof ConceptsRouteWithChildren
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  ForAgentsRoute: typeof ForAgentsRoute
  ForPartnersRoute: typeof ForPartnersRoute
  JourneyRoute: typeof JourneyRoute
  PackagesRoute: typeof PackagesRoute
  StyleGuideRoute: typeof StyleGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents': {
      id: '/for-agents'
      path: '/for-agents'
      fullPath: '/for-agents'
      preLoaderRoute: typeof ForAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-partners': {
      id: '/for-partners'
      path: '/for-partners'
      fullPath: '/for-partners'
      preLoaderRoute: typeof ForPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/': {
      id: '/concepts/'
      path: '/'
      fullPath: '/concepts/'
      preLoaderRoute: typeof ConceptsIndexRouteImport
      parentRoute: typeof ConceptsRoute
    }
    '/concepts/$slug': {
      id: '/concepts/$slug'
      path: '/$slug'
      fullPath: '/concepts/$slug'
      preLoaderRoute: typeof ConceptsSlugRouteImport
      parentRoute: typeof ConceptsRoute
    }
  }
}

interface ConceptsRouteChildren {
  ConceptsSlugRoute: typeof ConceptsSlugRoute
  ConceptsIndexRoute: typeof ConceptsIndexRoute
}

const ConceptsRouteChildren: ConceptsRouteChildren = {
  ConceptsSlugRoute: ConceptsSlugRoute,
  ConceptsIndexRoute: ConceptsIndexRoute,
}

const ConceptsRouteWithChildren = ConceptsRoute._addFileChildren(
  ConceptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConceptsRoute: ConceptsRouteWithChildren,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  ForAgentsRoute: ForAgentsRoute,
  ForPartnersRoute: ForPartnersRoute,
  JourneyRoute: JourneyRoute,
  PackagesRoute: PackagesRoute,
  StyleGuideRoute: StyleGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
